language: node_js

node_js:
  - "8"

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp cfg.example.json cfg.json

install:
  - npm install

script:
  - npm run lint
  - npm run test-node
